#! /bin/sh

# Monitor workspaces
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-I-1 -d 6 7 8 9 10

# Desknamer
/usr/bin/desknamer &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# SXHKD
sxhkd &
# Compton
compton --backend xrender --blur-background --blur-strength 8 &
# Polybar
$HOME/.config/polybar/launch.sh &
# Dunst
dunst &
# Feh
feh --bg-scale /home/karl/Assets/169654.jpg
# Wal
wal -i /home/karl/Assets/169654.jpg
# NetworkManager
nm-applet &

# Monitor configuration
xrandr --output DVI-I-1 --mode 1680x1050 --right-of HDMI-0 --set underscan on
xrandr --output HDMI-0 --mode 1680x1050 --left-of DVI-I-1 --primary

# Config
bspc config border_width                  2
bspc config window_gap                    5
bspc config top_padding                   25
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Colours
bspc config normal_border_color           "$color1"
bspc config active_border_color           "$color2"
bspc config focused_border_color          "$color15"
bspc config presel_feedback_color         "$color1"
bspc config presel_border_color           "$color1"
bspc config urgent_border_color 	      "#dd2727"

# Rules
bspc rule -a "GitAhead" state=floating
bspc rule -a "Slack" state=floating
bspc rule -a "Steam" state=floating
bspc rule -a "Microsoft Teams Notification" state=floating
